#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author : Benjamin
# @Time : 2018/3/6 20:07

# from appium import webdriver
# from Resource.Devices_config import *
# import time
# driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)

import unittest
from TestCase import NotLogin
from TestCase import AlreadyLogin
from Resource import HTMLTestRunner

if __name__ == '__main__':
    suite = unittest.TestSuite()
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(NotLogin))
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(AlreadyLogin))

    with open('HTMLReport.html', 'wb') as f:
        runner = HTMLTestRunner.HTMLTestRunner(stream=f,
                                               title='MathFunc Test Report',
                                               description='generated by HTMLTestRunner.',
                                               verbosity=2
                                               )
        runner.run(suite)



