# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('buttontype', models.CharField(max_length=100)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
