# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuinfo',
            name='buttontype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menuinfo',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuinfo',
            name='key',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menuinfo',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menuinfo',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menuinfo',
            name='uptime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuinfo',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
