# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_auto_20180326_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuinfo',
            name='button',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
