# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_menuinfo_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuinfo',
            name='level',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
